title: CSA Notes
description: "August 2023 to June 2024"
owner_name: Mati Danish
github_username: hsinaDitaM
baseurl: ""

#remote_theme: pages-themes/midnight@v0.2.0
theme: just-the-docs

color_scheme: nil
plugins:
  - jekyll-seo-tag

repository: hsinaDitaM/CSA_Notes

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
wsearch.heading_level: 1
#search.heading_level: 2 
#search.heading_level: 3
#search.heading_level: 4
#search.heading_level: 5
#search.heading_level: 6


search.previews: 5
