title: CSA Notes
description: "August 2023 to June 2024"
owner_name: Mati Danish
github_username: hsinaDitaM
baseurl: ""

#remote_theme: pages-themes/midnight@v0.2.0
theme: just-the-docs

color_scheme: dark
plugins:
  - jekyll-seo-tag

repository: hsinaDitaM/CSA_Notes
